# Generated by Django 4.1.7 on 2023-03-14 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Zа-яА-ЯёЁ]*$",
                        message="Имя может содержать только буквы",
                    )
                ],
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Zа-яА-ЯёЁ]*$",
                        message="Имя может содержать только буквы",
                    )
                ],
                verbose_name="Фамилия",
            ),
        ),
    ]
